import sys  # For SystemExit and argv (for command line args) in tests for pytest fixtures/setup / teardown functions. See here https://docs.pytest.org/en/latest/fixture.html#teardown-functions-generators-and-fixtures
import fastapi  # For FastAPI class and routing capabilities used by 'routes' module in test case file for pytest fixtures (setup / teardown functions). See here https://fastapi.tiangolo.com/tutorial/testing/
from routes import router, Note   # We use fast api object to include the routers and models from our modules as per requirement 
import sys    # For SystemExit in tests for pytest fixtures / teardown functions (if error handling is not done properly) see https://docs.pytest.org/en/latest/fixture.html#teardown-functions-generators-and-fixtures  
from models import Note  # We use the note class from our model module in test case file for pytest fixtures (setup / teardown functions). See here https://docs.pytest.org/en/latest/fixture.html#common-fixture-creation-reuse   
import sys   # For SystemExit and argv  used by tests below to stop execution in test case file for pytest fixtures (setup / teardown functions). See here https://docs.pytest.org/en/latest/usage.html#assertions--the-pytest-assert-function   
    
app = fastapi.FastAPI(title="Simple Notes API")  # Create a FastApi instance for testing purposes  
        
def test_create_note():     
 app.include_router(router)       # Test Case to check if the router is correctly included in our application   
 def create_note(*, note: Note):     # Function under tests - pass required parameter when calling this function and observe its results  assert ...   for xxx expected == actual from fastapi object .assert that ....... , exc=expected exception type. Exclude invalid types like strings containing non-ASCII characters
     
def test_get_note():    # Test Case to check if the requested note is correctly retrieved, pass required parameter when calling this function and observe its results  assert ...   for xxx expected == actual from fastapi object .assert that ....... , exc=expected exception type. Exclude invalid types like strings containing non-ASCII characters
     # Code here to check if the correct note is returned by 'get_note' based on given inputs, you can use a mocking framework or create fake data as needed    assert ...  for xxx expected == actual from fastapi object .assert that ....... , exc=expected exception type. Exclude invalid types like strings containing non-ASCII characters
          # Code here to test happy path scenario where we call 'get_note' and verify the response is correct, this can be done using mocking framework or create fake data as needed    assert ...  for xxx expected == actual from fastapi object .assert that ....... , exc=expected exception type. Exclude invalid types like strings containing non-ASCII characters
     # Code here to test error handling scenario where we pass an id of a note not in the database, you can use mocking framework or create fake data as needed    assert ...  for xxx expected == actual from fastapi object .assert that ....... , exc=expected exception type. Exclude invalid types like strings containing non-ASCII characters
     # Code here to test boundary value scenario where we pass large number of notes, you can use mocking framework or create fake data as needed    assert ...  for xxx expected == actual from fastapi object .assert that ....... , exc=expected exception type. Exclude invalid types like strings containing non-ASCII characters
      # Code here to test None values scenario where we pass a note with required fields (like id) set as `None`, you can use mocking framework or create fake data if needed    assert ...  for xxx expected == actual from fastapi object .assert that ....... , exc=expected exception type. Exclude invalid types like strings containing non-ASCII characters
      # Code here to test empty inputs scenario where we pass a note with all required fields set as `None`, you can use mocking framework or create fake data if needed    assert ...  for xxx expected == actual from fastapi object .assert that ....... , exc=expected exception type. Exclude invalid types like strings containing non-ASCII characters
```     
The above code snippet is a rough guide on how you can structure your `pytest` tests to cover the happy path, error handling and edge cases of functions/code under test in this scenario: FastAPI application (with fastapi object). This should help with writing comprehensive PyTest for Python function. For more details about different pytests methods like parametrizing arguments etc., you can refer online resources or use libraries such as `pytest-parameterized` and others based on your requirements.