"""
Comprehensive test suite for my_code.py
Generated by Pynguin - All test cases consolidated here
This file contains all generated test cases with various parameter combinations.
"""

import pytest
import sys
from pathlib import Path
import importlib.util

# Import testable module directly without triggering my_code.py
_testable_path = Path(__file__).parent / "my_code.testable.py"
_spec = importlib.util.spec_from_file_location("my_code_testable", _testable_path)
my_code_testable = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(my_code_testable)

