# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import simple_programs.calculator as module_0


def test_case_0():
    bool_0 = False
    with pytest.raises(ValueError):
        module_0.divide(bool_0, bool_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    bytes_0 = b"\x86\x01}1\xa4zao\xd6\xcda\x88\xbf\x95\xf58\xe4\xe3"
    var_0 = module_0.add(bytes_0, bytes_0)
    assert (
        var_0
        == b"\x86\x01}1\xa4zao\xd6\xcda\x88\xbf\x95\xf58\xe4\xe3\x86\x01}1\xa4zao\xd6\xcda\x88\xbf\x95\xf58\xe4\xe3"
    )
    module_0.multiply(var_0, var_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    str_0 = "@'v)_A*\t'Z"
    module_0.subtract(str_0, str_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    none_type_0 = None
    module_0.multiply(none_type_0, none_type_0)


def test_case_4():
    float_0 = 608.719
    var_0 = module_0.divide(float_0, float_0)
    assert var_0 == pytest.approx(1.0, abs=0.01, rel=0.01)
