# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import simple_programs.operations as module_0
import builtins as module_1


def test_case_0():
    bool_0 = False
    with pytest.raises(ValueError):
        module_0.average(bool_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    str_0 = "81fFpva6Ji\x0b"
    module_0.multiply(str_0, str_0)


def test_case_2():
    bool_0 = True
    float_0 = module_0.power(bool_0, bool_0)
    assert float_0 == 1


def test_case_3():
    float_0 = -2682.776902
    with pytest.raises(ValueError):
        module_0.power(float_0, float_0)


@pytest.mark.xfail(strict=True)
def test_case_4():
    bytes_0 = b'\xb9\xef"\xc2(A7k9$\x02\x1a\xf4\xda\x1f'
    module_0.is_even(bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_5():
    float_0 = 2335.75
    module_0.reverse_string(float_0)


def test_case_6():
    none_type_0 = None
    with pytest.raises(ValueError):
        module_0.reverse_string(none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_7():
    object_0 = module_1.object()
    list_0 = [object_0, object_0, object_0]
    module_0.average(list_0)
