# Test cases automatically generated by Pynguin (https://www.pynguin.eu).
# Please check them before you use them.
import pytest
import simple_programs.calculator as module_0


@pytest.mark.xfail(strict=True)
def test_case_0():
    bytes_0 = b"\x1d,\xb4\xc0\xc6%!K6\x007"
    module_0.divide(bytes_0, bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_1():
    none_type_0 = None
    module_0.add(none_type_0, none_type_0)


@pytest.mark.xfail(strict=True)
def test_case_2():
    bytes_0 = b"\r"
    module_0.subtract(bytes_0, bytes_0)


@pytest.mark.xfail(strict=True)
def test_case_3():
    list_0 = []
    module_0.multiply(list_0, list_0)


def test_case_4():
    complex_0 = 2829.4 + 2730.58182j
    var_0 = module_0.divide(complex_0, complex_0)
    assert var_0 == (1 + 0j)
    bool_0 = False
    module_0.subtract(complex_0, bool_0)
    bool_1 = False
    module_0.add(bool_1, bool_0)
    var_1 = module_0.multiply(bool_0, bool_1)
    assert var_1 == 0
    with pytest.raises(ValueError):
        module_0.divide(bool_0, bool_0)
